sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t codfishjoe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codfishjoe/docker-react npm run test
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"